---
title: "MAPC ACCESSABILITY MODELING"
output: html_document
---
This website will eventually summarize the MAPC West Station Area work conducted by Renaissance Planning Group for the Metropolitan Area Planning Council. This page will summarize the most basic areas of the project. Additionally a custom Bootstrap theme will be created to ensure the branding is correct for either MAPC or RPG depending on hosting requirements. Most of the text on this website is currently a placeholder.

## {.tabset}

### WHAT IS ACCESSIBILITY?

Multimodal accessibility is a new analytical lens helping city planners to gauge how well towns, cities and regions function, and to identify more holistic and integrated solutions. Multimodal accessibility correlates with all measures of successful places – environmental, economic, and social dimensions that support quality of life goals.  Renaissance continues to develop and apply multimodal accessibility methods and tools that span key elements of the built environments, most notably land development features and multimodal transportation networks. We incorporate people patterns, including location decisions and travel behavior into our analysis. 

### BASIC PROCESSING

Description of the basic level processing used in this analysis.

### ACCESSIBILITY AND TRAVEL BEHAVIOR

The multimodal accessibility approach enables analysis of existing multimodal opportunities within a given geographic scale as defined by both land use and existing multimodal infrastructure. These conditions correlate with estimated walk, bike and transit trip demand rates. This type of analysis can be used to help planners identify specific land use or infrastructure interventions to increase multimodal accessibility and thereby the likely walking, biking and transit trip opportunities. For this corridor, the analysis provided additional insights to help guide future planning for Bus Rapid Transit (BRT).

This work will enable MDOT to continue using the multimodal accessibility approach and tools for a wide range of purposes, from multimodal investment analyses and project prioritization to traffic impact studies and working with local jurisdictions in support of Plan Maryland, the state’s comprehensive land use plan. This seminal project has also led to additional work with other jurisdictions in the greater Washington region to incorporate multimodal accessibility as a key performance measure that can be used to guide project priorities and investments including an accessibility pilot study for Arlington County, Virginia and the creation of an accessibility metric for the Virginia Department of Transportation on the HB2 statewide funding prioritization process.