---
title: "K FACTORS IN TRIP DISTRIBUTION"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, 
                      fig.pos = 'H', fig.cap=T)
```

The accessibility-based model's estimates of trips by mode are generated by
applying the mode choice models - estimate based on  regional household survey 
data - to accessibility scores and household characteristics. The resulting 
estimates generally reflect the trends and tendencies revealed in the survey
records. However, when compared to mode shares generated by the regional 
travel demand model, some discrepancies were observed. Notably, the 
accessibility-based model tended to estimate higher utilization of transit and
non-motorized modes than the regional model.

To ensure consistency between the two modeling frameworks, the accessibility-based
mode choice estimates were factored to more closely approximate the regional model's
outputs. The factors (called "K factor" in this analysis) were calibrated such
that the LRTP scenario outputs from the accessibility model would resemble the 
corresponding estimates generated by the regional model. These factors were then 
applied in the same manner across all scenarios. 

Below are several relevant notes for understanding, applying, and interpreting
the K factors.

- The K factors are provided as a scalar vector in the script that executes the
distribution proces (Step 6).  

-	The K factors were estimated based on daily trips. The distribution process 
also factors trip estimates down to period-specific (AM) trips using period 
factors that vary by purpose. 

-	Period and K factors are applied when developing trip distribution seeds.
In effect, this means the distribution process starts with production-end mode 
shares matching regional model production-end mode shares for the LRTP scenario
(since the factors are calibrated to that scenario).

- The distribution process balances the full multimodal trip table, constraining
productions and attractions at the person trip level only. Trips by mode are 
allowed to float while total person trips must match the trip generation outputs.


   - The attraction-end mode choice models provide a guidepost for seeding the
   distribution process, which is then run across all modes together with the 
   balancing factors focusing only on total person trips. Thus, the distribution
   is seeded with expectations about where trips are beginning and ending by mode 
   and uses the trip generation outputs to ensure the right numbers of person 
   trip productions and attractions are maintained through the iterative
   proportional fitting (IPF) process used for balancing the trip table.
   
   - As balancing unfolds, the factoring up or down of certain zones retains 
   the mode splits to/from each zone, but it can result in aggregate shifts in 
   mode shares relative to the mode choice model outputs.
   
-	The distribution process described above can dilute the effect of the K factors.
For example, the non-motorized trips in the window area hover around 35-40 percent
despite the initial factoring to lower those estimates by 5-10 percentage points.




