---
title: "ACCESSIBILITY MODEL DOCUMENTATION"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, 
                      fig.pos = 'H', fig.cap=T)
```

This page provides an overview of the key documents detailing the modeling
procedures and foundational relationships used in the accessibility-based
sketch model. The documents are ordered in a way that roughly matches the
model application steps. A brief description of each document is provided
below.

- **[Decay rates in accessibility summarization](./NaiveEstimatorsV1.html):** 
Decay refers to the concept that travel is less likely to occur between two zones 
if the cost to travel between them is high. Specific rates of decay vary by mode 
and travel purpose. This page provides the details of the data and model fitting
techniques used to define decay rates for accessibility summarization and trip 
distribution in the West Station analysis.

- **Trip generation**
  
  - **[Trip generation rates](./TripGen.html):** This page provides a basic overview of the trip
  generation process, including a rundown of trip generation rates and the
  procedures used to cross-classify households for trip generation purposes.
  
  - **[Literature review: Trip generation and the build environment](./WhitePaper_TripGenAndBuiltEnviron.pdf):** 
  This is a brief review of academic and industry literature assessing how different
  characteristics of the built environment influence trip generation rates. The 
  literature is ambivalent about the role of accessibility and related measures 
  in altering person trip generation rates. Rather, accessibility has a more
  pronounced influence on mode choice. For this reason, the West Station analysis
  does not use accessibility scores to alter trip generation rates, focusing
  instead on mode choice and trip distribution applications.
  
- **Mode Choice**

  - **[Overview of model sensitivities](./Model_Sensitivities_Report.html):** This
  page offers a high-level summary of the factors that influence travel
  behavior outputs generated by the accessibility-based mode, focusing on the
  factors and parameters that influence accessibility scores and mode choice 
  model results.
  
  - **[Mode choice model detailed report](./Mode_Choice_Report.html):** This
  report presents the details of the mode choice modeling conducted for the
  Boston region to develop behavioral relationships based on accessibility scores
  and demographic data.
  
- **Trip distribution**

  - **[K factors](./Kfactors.html):** This page describes adjustments made to raw
  outputs from the accessibility-based mode choice models prior to distribution
  to generate mode share estimates that better approximate those generated by
  the regional travel demand model. This adjustment helps maintain 
  consistency in trip-making expectations established by these two different
  modeling frameworks.
  
  - *Potential future enhancement* - **[Trip survival curves](./TripDecayV2.html):** 
  This report describes an approach to enrich the trip distribution process
  using survival (or proportional hazards) modeling techniques. The modeling
  framework was developed as part of the West Station analysis but not deployed
  due to time and computational constraints. The potential benefits of this
  enhancement to the decay curves used in the trip distribution step include
  more nuanced responses to travel opportunities based on cost parameters and
  household characteristics beyond what can be obtained using the generalized
  cost constructs used in the pilot project application.

- **[TNC Trips](./TNC_Report.html):** This report describes the data and methods used
in developing estimates of TNC trip-making based on the sketch model trip table
outputs. The approach focuses on assessing which OD pairs are likely to have
trips (by a given mode and for a given travel purpose) replaced by TNC trips
based on relative generalized cost distributions for the observed mode and the
potential TNC trip.


