---
title: "TRAVEL BEHAVIOR AND ACCESSIBILITY"
output: html_document
---
```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, 
                      fig.pos = 'H', fig.cap=T)
```

A more in depth summary of how accessibility is affected by travel behaviors and other factors.

Will include a interactive network diagram illustrating these interactions

```{r Setup}
library(tidyverse)
library(sf)
library(tmap)
library(shiny)
library(rpgcolorsr)
tmap_mode("view")

zones <- read_sf("./data/mapping/MAPC_Zones_simp.shp")
data  <- read_csv("./data/access_to_jobs_auto_HBO.csv")

zones <- left_join(zones,data)

tot_emp_pal  <- rpg_color_pal("rpg_orange_ramp")(5)
retail_pal   <- rpg_color_pal("chartreuse_ramp")(5)
service_pal  <- rpg_color_pal("rpg_blue_ramp")(5)
basic_pal    <- rpg_color_pal("red_ramp")(5)
tot_enr_pal  <- rpg_color_pal("sea_green_ramp")(5)
```

## AUTO ACCESS TO JOBS HBO
## {.tabset}

### TOTAL EMPLOYMENT
```{r, eval = TRUE}
tm_shape(zones) + tm_polygons(col = "Total Emp-Purpose-HBO",
                              palette = tot_emp_pal,
                              n = 5,
                              style = "pretty",
                              lwd = 0.1,
                              title = "Total Employment")
```

### RETAIL EMPLOYMENT
```{r, eval = TRUE}
tm_shape(zones) + tm_polygons(col = "Retail-Purpose-HBO",
                              palette = retail_pal,
                              n = 5,
                              style = "pretty",
                              lwd = 0.1,
                              title = "Retail")
```

### SERVICE EMPLOYMENT
```{r, eval = TRUE}
tm_shape(zones) + tm_polygons(col = "Service-Purpose-HBO",
                              palette = service_pal,
                              n = 5,
                              style = "pretty",
                              lwd = 0.1,
                              title = "Service")
```

### BASIC EMPLOYMENT
```{r, eval = TRUE}
tm_shape(zones) + tm_polygons(col = "Basic-Purpose-HBO",
                              palette = basic_pal,
                              n = 5,
                              style = "pretty",
                              lwd = 0.1,
                              title = "Basic")
```

### TOTAL ENROLL
```{r, eval = TRUE}
tm_shape(zones) + tm_polygons(col = "TotEnroll-Purpose-HBO",
                              palette = tot_enr_pal,
                              n = 5,
                              style = "pretty",
                              lwd = 0.1,
                              title = "TotEnroll")
```

# <br />
We will include other data here

```{r Map 1, eval = FALSE}
zones <- read_sf("./data/mapping/MAPC_Zones_simp.shp")
data  <- read_csv("./data/access_to_jobs_auto_HBO.csv")

zones <- left_join(zones,data)

tot_emp_pal  <- rpg_color_pal("rpg_orange_ramp")(5)
retail_pal   <- rpg_color_pal("chartreuse_ramp")(5)
service_pal  <- rpg_color_pal("rpg_blue_ramp")(5)
basic_pal    <- rpg_color_pal("red_ramp")(5)
tot_enr_pal  <- rpg_color_pal("sea_green_ramp")(5)


shinyApp(

  ui = fluidPage(
    titlePanel("Access to Jobs"),
     tmapOutput("map1"),
     selectInput("variable", h4("Variable:"),
                 choices = list("Total Employment",
                                "Retail",
                                "Service",
                                "Basic",
                                "TotEnroll")),
    
              helpText("Select the variable visualized in the map, 
                       updates occur in real time")
    ),


  server = function(input, output) {
    observe({
    output$map1 <-  renderTmap({
       var <- switch(input$variable,
                     "Total Employment" = "Total Emp-Purpose-HBO",
                     "Retail"           = "Retail-Purpose-HBO",
                     "Service"          = "Service-Purpose-HBO",
                     "Basic"            = "Basic-Purpose-HBO",
                     "TotEnroll"        = "TotEnroll-Purpose-HBO") 
       
       pal <- switch(input$variable,
                     "Total Employment" = tot_emp_pal,
                     "Retail"           = retail_pal, 
                     "Service"          = service_pal,
                     "Basic"            = basic_pal,  
                     "TotEnroll"        = tot_enr_pal,)
       
       tm_shape(zones) + tm_polygons(col = var, 
                                     palette = pal,
                                     n = 5,
                                     style = "pretty",
                                     lwd = 0.1,
                                     title = input$variable)
    })
    }) 
  },

  options = list(height = 750)
)
```
